### ISSUE TITLE
Forbidden calling from Perl.

### ISSUE THREAD

**Issue by RussellMcOrmond** [c7a/cihm-cantaloupe#24]
The Perl calls use the Authorization header, and it is possible that the new version of Cantaloupe has a problem with this header as it did with the cookies.  It seems that calls to Cantaloupe fail with Hammer.

**Comment by RussellMcOrmond** [comment]
Sample Hammer logs....

```
2020/08/21 12:50:07 - WARN {CIHM.TDR} [CIHM::Meta::Hammer::Worker::warnings] oocihm.N_00004_19160224: Data was $VAR1 = [
          '403 Forbidden

Forbidden


edu.illinois.library.cantaloupe.resource.ResourceException: Forbidden
	at edu.illinois.library.cantaloupe.resource.AbstractResource.authorize(AbstractResource.java:288)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.InformationResource.doGET(InformationResource.java:63)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:98)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:36)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1391)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:760)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)

'
        ];
  at /usr/local/lib/perl5/site_perl/5.30.2/Role/REST/Client/Serializer.pm line 80.
2020/08/21 12:50:07 - WARN {CIHM.TDR} [CIHM::Meta::Hammer::Worker::warnings] oocihm.N_00004_19160224: Couldn't deserialize data with application/json: garbage after JSON object, at character offset 5 (before "orbidden\n\nForbidde...") at /usr/local/lib/perl5/site_perl/5.30.2/Data/Serializer/JSON.pm line 17.
```


Smelter, which also uses https://github.com/crkn-rcdr/CIHM-Meta/blob/master/lib/CIHM/Meta/REST/cantaloupe.pm is giving similar errors.

**Comment by SaschaAdler** [comment]
I think I changed the header contents to expect `Bearer $TOKEN` instead of `C7A2 $TOKEN` (or whatever it was), for consistency's sake. Could we change the tools to use that?

**Comment by RussellMcOrmond** [comment]
There aren't that many references, if we wanted to make that change now.


https://github.com/search?q=org%3Acrkn-rcdr+C7A2&type=Code

I believe several of these are projects that could be archived, as I don't think we plan to use them any more.

https://github.com/crkn-rcdr/cihm-jwt
https://github.com/crkn-rcdr/cihm-file-access
https://github.com/crkn-rcdr/cihm-cookie-authorizer




To update would be 

https://github.com/crkn-rcdr/CIHM-Meta/blob/master/lib/CIHM/Meta/REST/UserAgent.pm
https://github.com/crkn-rcdr/CIHM-TDR/blob/master/lib/CIHM/TDR/REST/UserAgent.pm

**Comment by SaschaAdler** [comment]
Agreed. I can archive those projects.

**Comment by RussellMcOrmond** [comment]
@SaschaAdler , is it possible for you to check the context["request_headers"] the same way you did for cookies to see if the token is in the right place.   The above patch to the metadata bus (module used by Hammer/Smelter) didn't fix the issue.

**Comment by RussellMcOrmond** [comment]
I'm going to leave the other useragent for now, as I don't think it is being used https://github.com/crkn-rcdr/CIHM-TDR/issues/9

**Comment by SaschaAdler** [comment]
Turns out I can't archive those projects, I think because they were ported over from the Canadiana GitHub.

I'll look into the token not working.

**Comment by SaschaAdler** [comment]
My guess is that the issuer isn't set up right, although it's hard to tell without the Cantaloupe logs for the failed requests.

The JWT `iss` field needs to be set to `CAP`, and I'm not sure how/where in the CIHM::Meta code this happens. See:
https://github.com/crkn-rcdr/cihm-cantaloupe/blob/b6dcd5e81bb01de5bfe4ff1480b2ff164eb8eb1b/delegates.rb#L42-L46

**Comment by RussellMcOrmond** [comment]
The iss is set to CAP.

https://github.com/crkn-rcdr/CIHM-Meta/blob/225fafc24ea05b5b66fcdc569d671c927b287ca7/lib/CIHM/Meta/REST/UserAgent.pm#L33-L35

Now that there is no other option, I'll update to hard-code 'CAP' so there would be no potential misconfiguration.

**Comment by RussellMcOrmond** [comment]
```
16:47:01.403 [qtp1032000752-139588] INFO  e.i.l.c.r.i.v.InformationResource - Handling GET /iiif/2/oocihm.N_00004_19160224%2Fdata%2Fsip%2Fdata%2Ffiles%2F0016.jpg/info.json
JWT Decode error: Invalid segment encoding
Unauthorized: JWT could not be validated.
16:47:01.407 [qtp1032000752-139588] INFO  e.i.l.c.r.ErrorResource - Handling GET /iiif/2/oocihm.N_00004_19160224%2Fdata%2Fsip%2Fdata%2Ffiles%2F0016.jpg/info.json
```

**Comment by RussellMcOrmond** [comment]
Added in an additional 'puts' to see what I could find...

```
17:15:15.761 [qtp1032000752-103] INFO  e.i.l.c.r.i.v.InformationResource - Handling GET /iiif/2/oocihm.N_00004_19160224%2Fdata%2Fsip%2Fdata%2Ffiles%2F0016.jpg/info.json
JWT Decode error: Invalid segment encoding
Token: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1aWRzIjpbIi4qIl0sImlzcyI6IkNBUCJ9.q_LWtrSo62kvXeRY20agpAEAWGGetXqI0fUV9xGyptM
Unauthorized: JWT could not be validated.
17:15:15.771 [qtp1032000752-103] INFO  e.i.l.c.r.ErrorResource - Handling GET /iiif/2/oocihm.N_00004_19160224%2Fdata%2Fsip%2Fdata%2Ffiles%2F0016.jpg/info.json
```

Will check against what is set on the client side later...

**Comment by RussellMcOrmond** [comment]
I believe the latest commit can close this issue.
